author: "Prof. Luiz T. F. Eleno"
author_email: luizeleno@usp.br
title: "Demar :: EEL :: USP"
name: Departamento de Engenharia de Materiais
name_en: Materials Engineering Department
unidade:
  sigla: EEL
  nome: Escola de Engenharia de Lorena
universidade:
  nome:  Universidade de São Paulo
  sigla: USP
short_name: Demar
email: lom@eel.usp.br
description: >- # this means to ignore newlines until "baseurl:"
 O Departamento de Engenharia de Materiais (DEMAR) iniciou suas atividades
 em 1978 com o Projeto Nióbio (veja o Histórico) e desde 2006 integra a
 Escola de Engenharia de Lorena (EEL), uma das Unidades de Ensino e Pesquisa
 da Universidade de São Paulo (USP). Atualmente o DEMAR conta com 34 docentes,
 31 dos quais com doutorado. Desses, 12 têm título de Livre-Docente e 13 são
 bolsistas de produtividade do CNPq. O DEMAR coordena e ministra as disciplinas
 específicas dos cursos de  graduação em Engenharia Física e Engenharia de
 Materiais, além de disciplinas relacionadas à área de materiais do Ciclo
 Básico da EEL/USP. Docentes do departamento também ministram disciplinas e
 orientam teses e dissertações no Programa de Pós Graduação em Engenharia de
 Materiais (mestrado e doutorado) e no Programa de Pós Graduação em Projetos
 Educacionais de Ciências (mestrado profissional). As instalações do DEMAR
 localizam-se na Área II da EEL/USP.
baseurl: /Demar # the subpath of your site, e.g. /blog
url: http://www.demar.eel.usp.br # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: "UA-143315747-1"
# github:  luizeleno    

# location of built site:
destination: docs/ #docs/

# Build settings
#markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-figure
  - jekyll-seo-tag
  - jekyll-youtube
  - jekyll-paginate-v2

collections:
  docentes:
    output: true
    permalink: /docentes/:name.html
  faculty:
    output: true
    permalink: /en/docentes/:name.html
  labs:
    output: true
    permalink: /labs/:name.html
  labs_en:
    output: true
    permalink: /en/labs/:name.html
  noticias:
    output: true
    permalink: /news/:name.html
  news:
    output: true
    permalink: /en/news/:name.html
  correios:
    output: false

language: [br, en]
def_lang: br

pagination:
  enabled: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      lang: br
  -
    scope:
      path: ""
      type: posts
    values:
        layout: post
        author: Luiz T. F. Eleno
        categories: noticias
  -
    scope:
      path: ""
      type: docentes
    values:
        layout: docente
        staff:
          br: Professor Doutor
          en: Assistant Professor
        abrev: Prof. Dr.
        profile_style: text
  -
    scope:
      path: ""
      type: faculty
    values:
        layout: faculty
        lang: en
        staff:
          br: Professor Doutor
          en: Assistant Professor
        abrev: Prof. Dr.
        profile_style: text
  -
    scope:
      path: ""
      type: news
    values:
      layout: post
      lang: en
      image: "/assets/images/demar/Fachada-banner.jpg"
  -
    scope:
      path: ""
      type: noticias
    values:
      layout: post
      lang: br
      image: "/assets/images/demar/Fachada-banner.jpg"
  -
    scope:
      path: ""
      type: labs
    values:
        layout: lab
  -
    scope:
      path: ""
      type: labs_en
    values:
        layout: lab
        lang: en
  -
    scope:
      path: "en/*"
    values:
      lang: en

sass:
  load_paths:
    - css
    - js
  style: compressed

#emoji:
#  src: "/assets/images/emoji"

exclude:
  - Rakefile
  - README.md
  - CNAME
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .git
  - .ftpconfig
  - webmin-setup.out
